//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bankify
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tranzaction
    {
        public int transaction_id { get; set; }
        public string from_iban { get; set; }
        public string to_iban { get; set; }
        public double amount { get; set; }
        public string currency { get; set; }
        public System.DateTime transaction_date { get; set; }
        public int bank_account_from_id { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
    }
}
